### ISSUE TITLE
Formatierung auf der Jobs Unterseite

### ISSUE THREAD

**Issue by MrKaya** [Xperients/Xperients.github.io#10]
Formatierung von "Interessiert? Dann senden Sie Ihre aussagekräftige Bewerbung bitte an: XPERIENTS UG (haftungsbeschränkt) i. Gr. Alexander Xavier Fichtl Kükenkamp 22 29590 Rätzlingen E-Mail: info@xperients.de" ist zerschossen.

Und "E-Mail:" sollte hier nicht stehen.

Darstellung sollte so sein:

Interessiert? Dann senden Sie Ihre aussagekräftige Bewerbung bitte an: 

XPERIENTS UG (haftungsbeschränkt) i. Gr. 
Alexander Xavier Fichtl 
Kükenkamp 22 
29590 Rätzlingen 
info@xperients.de

**Comment by Farson** [comment]
done
